DELETE FROM LOAD_PLAN_BOX;
DELETE FROM USER_INVENTORY_ITEM;
DELETE FROM USER_FEEDBACK;
DELETE FROM USER;
DELETE FROM BOX_SIZE;
DELETE FROM EXPERT_TIP;
DELETE FROM USER_ROLE;
DELETE FROM ROLE;
DELETE FROM TRUCK;

